import json
def build_pom_class_prompt(intent_json, generated_methods, existing_class_context=None):
    """
    Prompt to generate or extend a Playwright POM class.

    Args:
        intent_json (dict): Parsed user intent with UI elements and steps.
        generated_methods (str): Methods generated by the LLM in Prompt 1.
        existing_class_context (str, optional): Existing POM class code if extending.

    Returns:
        str: Final prompt string.
    """
    prompt = []

    prompt.append("You are a Playwright test automation engineer.")
    prompt.append("Generate a Page Object Model (POM) class in TypeScript based on the provided UI intent and page methods.")

    # Add context about the UI or page
    if "ui_elements" in intent_json:
        prompt.append("\nUI Elements to include (e.g. input fields, buttons, labels):")
        prompt.append(json.dumps(intent_json["ui_elements"], indent=2))

    # Include the methods generated earlier
    prompt.append("\nGenerated Page Methods (from previous step):")
    prompt.append(generated_methods)

    # Mention if we are extending an existing class
    if existing_class_context:
        prompt.append("\nExtend the following existing POM class:")
        prompt.append(existing_class_context)
        prompt.append("\nOnly add the new methods. Preserve existing structure and class name.")

    else:
        # New class
        class_name = intent_json.get("class_name", "CaseSearchPage")
        prompt.append(f"\nCreate a new class named `{class_name}`.")
        prompt.append("Include a constructor that takes `page: Page` from Playwright and initialize locators.")
        prompt.append("Use Playwright best practices like `this.searchInput = page.locator(...)`.")

    prompt.append("\nOutput only the final TypeScript class code — no explanations.")

    return "\n".join(prompt)

def build_stepdef_class_prompt(user_intent, generated_methods, pom_class_name, existing_stepdefs_context=None):
    """
    Prompt to generate or extend a Cucumber Step Definitions file using Playwright and the POM methods.

    Args:
        user_intent (dict): Contains the Gherkin user story and any parsed steps.
        generated_methods (str): Methods previously generated for the POM class.
        pom_class_name (str): Name of the corresponding POM class to import and use.
        existing_stepdefs_context (str, optional): Existing step definition file contents if extending.

    Returns:
        str: Final prompt for GenAI to generate the Step Definitions file.
    """
    prompt = []

    prompt.append("You are a QA engineer using Playwright with Cucumber in TypeScript.")
    prompt.append("Generate or extend a Step Definitions file based on the following user story and page object methods.")

    # Add the user story or scenario steps
    if "userStory" in user_intent:
        prompt.append("\nGherkin User Story:")
        prompt.append(user_intent["userStory"])

    # Add parsed instructions if available
    if "instructions" in user_intent:
        prompt.append("\nCustom Instructions:")
        prompt.append(user_intent["instructions"])

    # Add the generated page methods to use
    prompt.append("\nAvailable Page Methods:")
    prompt.append(generated_methods)

    # Add context for existing stepdefs if applicable
    if existing_stepdefs_context:
        prompt.append("\nExtend the following existing step definition file:")
        prompt.append(existing_stepdefs_context)
        prompt.append("\nAdd new step definitions only. Do not duplicate existing ones.")
    else:
        prompt.append(f"\nUse the page object class `{pom_class_name}`.")
        prompt.append("Import it and initialize inside the `Before` or `World` context if needed.")

    prompt.append("\nUse Cucumber annotations like `Given`, `When`, and `Then`.")
    prompt.append("Use Playwright best practices with async/await and proper locator usage.")
    prompt.append("Return only the final step definition code in TypeScript — no explanations.")

    return "\n".join(prompt)
